module.exports = {
    states:
        [
            {
                stateName: "آذربایجان شرقی", cities:
                    [
                        { cityName: "کشکسرای" },
                        { cityName: "سهند" },
                        { cityName: "سیس" },
                        { cityName: "دوزدوزان" },
                        { cityName: "تیمورلو" },
                        { cityName: "صوفیان" },
                        { cityName: "سردرود" },
                        { cityName: "هادیشهر" },
                        { cityName: "هشترود" },
                        { cityName: "زرنق" },
                        { cityName: "ترکمانچای" },
                        { cityName: "ورزقان" },
                        { cityName: "تسوج" },
                        { cityName: "زنوز" },
                        { cityName: "ایلخچی" },
                        { cityName: "شرفخانه" },
                        { cityName: "مهربان" },
                        { cityName: "مبارک شهر" },
                        { cityName: "تیکمه داش" },
                        { cityName: "باسمنج" },
                        { cityName: "سیه رود" },
                        { cityName: "میانه" },
                        { cityName: "خمارلو" },
                        { cityName: "خواجه" },
                        { cityName: "بناب مرند" },
                        { cityName: "قره آغاج" },
                        { cityName: "وایقان" },
                        { cityName: "مراغه" },
                        { cityName: "ممقان" },
                        { cityName: "خامنه" },
                        { cityName: "خسروشاه" },
                        { cityName: "لیلان" },
                        { cityName: "نظرکهریزی" },
                        { cityName: "اهر" },
                        { cityName: "بخشایش" },
                        { cityName: "آقکند" },
                        { cityName: "جوان قلعه" },
                        { cityName: "کلیبر" },
                        { cityName: "مرند" },
                        { cityName: "اسکو" },
                        { cityName: "شندآباد" },
                        { cityName: "شربیان" },
                        { cityName: "گوگان" },
                        { cityName: "بستان آباد" },
                        { cityName: "تبریز" },
                        { cityName: "جلفا" },
                        { cityName: "اچاچی" },
                        { cityName: "هریس" },
                        { cityName: "یامچی" },
                        { cityName: "خاروانا" },
                        { cityName: "کوزه کنان" },
                        { cityName: "خداجو(خراجو)" },
                        { cityName: "آذرشهر" },
                        { cityName: "شبستر" },
                        { cityName: "سراب" },
                        { cityName: "ملکان" },
                        { cityName: "بناب" },
                        { cityName: "هوراند" },
                        { cityName: "کلوانق" },
                        { cityName: "ترک" },
                        { cityName: "عجب شیر" },
                        { cityName: "آبش احمد" }
                    ]
            },
            {
                stateName: "آذربایجان غربی", cities:
                    [
                        { cityName: "قره ضیاءالدین" },
                        { cityName: "تازه شهر" },
                        { cityName: "نالوس" },
                        { cityName: "ایواوغلی" },
                        { cityName: "شاهین دژ" },
                        { cityName: "گردکشانه" },
                        { cityName: "باروق" },
                        { cityName: "سیلوانه" },
                        { cityName: "بازرگان" },
                        { cityName: "نازک علیا" },
                        { cityName: "ربط" },
                        { cityName: "تکاب" },
                        { cityName: "دیزج دیز" },
                        { cityName: "سیمینه" },
                        { cityName: "نوشین" },
                        { cityName: "میاندوآب" },
                        { cityName: "مرگنلر" },
                        { cityName: "سلماس" },
                        { cityName: "آواجیق" },
                        { cityName: "قطور" },
                        { cityName: "محمودآباد" },
                        { cityName: "خوی" },
                        { cityName: "نقده" },
                        { cityName: "سرو" },
                        { cityName: "خلیفان" },
                        { cityName: "پلدشت" },
                        { cityName: "میرآباد" },
                        { cityName: "اشنویه" },
                        { cityName: "زرآباد" },
                        { cityName: "بوکان" },
                        { cityName: "پیرانشهر" },
                        { cityName: "چهاربرج" },
                        { cityName: "قوشچی" },
                        { cityName: "شوط" },
                        { cityName: "ماکو" },
                        { cityName: "سیه چشمه" },
                        { cityName: "سردشت" },
                        { cityName: "کشاورز" },
                        { cityName: "فیرورق" },
                        { cityName: "محمدیار" },
                        { cityName: "ارومیه" },
                        { cityName: "مهاباد" },
                        { cityName: "قره ضیاءالدین" }
                    ]
            },
            {
                stateName: "اردبیل", cities:
                    [
                        { cityName: "آبی بیگلو" },
                        { cityName: "پارس آباد" },
                        { cityName: "فخراباد" },
                        { cityName: "کلور" },
                        { cityName: "نیر" },
                        { cityName: "اردبیل" },
                        { cityName: "اسلام اباد" },
                        { cityName: "تازه کندانگوت" },
                        { cityName: "مشگین شهر" },
                        { cityName: "جعفرآباد" },
                        { cityName: "نمین" },
                        { cityName: "اصلاندوز" },
                        { cityName: "مرادلو" },
                        { cityName: "خلخال" },
                        { cityName: "کوراییم" },
                        { cityName: "هیر" },
                        { cityName: "گیوی" },
                        { cityName: "گرمی" },
                        { cityName: "لاهرود" },
                        { cityName: "هشتجین" },
                        { cityName: "عنبران" },
                        { cityName: "تازه کند" },
                        { cityName: "قصابه" },
                        { cityName: "رضی" },
                        { cityName: "سرعین" },
                        { cityName: "بیله سوار" },
                        { cityName: "آبی بیگلو" }
                    ]
            },
            {
                stateName: "اصفهان", cities:
                    [
                        { cityName: "ابریشم" },
                        { cityName: "گزبرخوار" },
                        { cityName: "زیار" },
                        { cityName: "زرین شهر" },
                        { cityName: "گلشن" },
                        { cityName: "پیربکران" },
                        { cityName: "خالدآباد" },
                        { cityName: "سجزی" },
                        { cityName: "گوگد" },
                        { cityName: "تیران" },
                        { cityName: "ونک" },
                        { cityName: "دهق" },
                        { cityName: "زواره" },
                        { cityName: "کاشان" },
                        { cityName: "ابوزیدآباد" },
                        { cityName: "اصغرآباد" },
                        { cityName: "بافران" },
                        { cityName: "شهرضا" },
                        { cityName: "خور" },
                        { cityName: "مجلسی" },
                        { cityName: "هرند" },
                        { cityName: "فولادشهر" },
                        { cityName: "کمشچه" },
                        { cityName: "کلیشادوسودرجان" },
                        { cityName: "لای بید" },
                        { cityName: "قهجاورستان" },
                        { cityName: "چرمهین" },
                        { cityName: "رزوه" },
                        { cityName: "فریدونشهر" },
                        { cityName: "طرق رود" },
                        { cityName: "نصرآباد" },
                        { cityName: "برزک" },
                        { cityName: "سفیدشهر" },
                        { cityName: "سمیرم" },
                        { cityName: "گلدشت" },
                        { cityName: "اردستان" },
                        { cityName: "جوشقان قالی" },
                        { cityName: "بویین ومیاندشت" },
                        { cityName: "کرکوند" },
                        { cityName: "درچه" },
                        { cityName: "انارک" },
                        { cityName: "دولت آباد" },
                        { cityName: "ایمانشهر" },
                        { cityName: "گرگاب" },
                        { cityName: "حسن اباد" },
                        { cityName: "سده لنجان" },
                        { cityName: "حبیب آباد" },
                        { cityName: "بهاران شهر" },
                        { cityName: "میمه" },
                        { cityName: "تودشک" },
                        { cityName: "گلشهر" },
                        { cityName: "رضوانشهر" },
                        { cityName: "داران" },
                        { cityName: "علویجه" },
                        { cityName: "نیک آباد" },
                        { cityName: "مشکات" },
                        { cityName: "آران وبیدگل" },
                        { cityName: "خوانسار" },
                        { cityName: "نجف آباد" },
                        { cityName: "منظریه" },
                        { cityName: "فرخی" },
                        { cityName: "دیزیچه" },
                        { cityName: "اژیه" },
                        { cityName: "زاینده رود" },
                        { cityName: "خورزوق" },
                        { cityName: "قهدریجان" },
                        { cityName: "شاهین شهر" },
                        { cityName: "بهارستان" },
                        { cityName: "چمگردان" },
                        { cityName: "دهاقان" },
                        { cityName: "برف انبار" },
                        { cityName: "بادرود" },
                        { cityName: "کوهپایه" },
                        { cityName: "گلپایگان" },
                        { cityName: "عسگران" },
                        { cityName: "حنا" },
                        { cityName: "کهریزسنگ" },
                        { cityName: "مهاباد" },
                        { cityName: "کامو و چوگان" },
                        { cityName: "افوس" },
                        { cityName: "زیباشهر" },
                        { cityName: "کوشک" },
                        { cityName: "نایین" },
                        { cityName: "سین" },
                        { cityName: "زازران" },
                        { cityName: "مبارکه" },
                        { cityName: "ورزنه" },
                        { cityName: "ورنامخواست" },
                        { cityName: "شاپورآباد" },
                        { cityName: "فلاورجان" },
                        { cityName: "وزوان" },
                        { cityName: "اصفهان" },
                        { cityName: "باغ بهادران" },
                        { cityName: "چادگان" },
                        { cityName: "دامنه" },
                        { cityName: "نطنز" },
                        { cityName: "محمدآباد" },
                        { cityName: "نیاسر" },
                        { cityName: "نوش آباد" },
                        { cityName: "کمه" },
                        { cityName: "جوزدان" },
                        { cityName: "قمصر" },
                        { cityName: "جندق" },
                        { cityName: "طالخونچه" },
                        { cityName: "خمینی شهر" },
                        { cityName: "باغشاد" },
                        { cityName: "دستگرد" },
                        { cityName: "ابریشم" }
                    ]
            },
            {
                stateName: "البرز", cities:
                    [
                        { cityName: "فردیس" },
                        { cityName: "چهارباغ" },
                        { cityName: "آسارا" },
                        { cityName: "کرج" },
                        { cityName: "طالقان" },
                        { cityName: "شهرجدیدهشتگرد" },
                        { cityName: "محمدشهر" },
                        { cityName: "مشکین دشت" },
                        { cityName: "نظرآباد" },
                        { cityName: "هشتگرد" },
                        { cityName: "ماهدشت" },
                        { cityName: "اشتهارد" },
                        { cityName: "کوهسار" },
                        { cityName: "گرمدره" },
                        { cityName: "تنکمان" },
                        { cityName: "گلسار" },
                        { cityName: "کمال شهر" },
                        { cityName: "فردیس" }
                    ]
            },
            {
                stateName: "ایلام", cities:
                    [
                        { cityName: "دلگشا" },
                        { cityName: "آبدانان" },
                        { cityName: "شباب" },
                        { cityName: "موسیان" },
                        { cityName: "بدره" },
                        { cityName: "ایلام" },
                        { cityName: "ایوان" },
                        { cityName: "مهران" },
                        { cityName: "آسمان آباد" },
                        { cityName: "پهله" },
                        { cityName: "مهر" },
                        { cityName: "سراب باغ" },
                        { cityName: "بلاوه" },
                        { cityName: "میمه" },
                        { cityName: "دره شهر" },
                        { cityName: "ارکواز" },
                        { cityName: "مورموری" },
                        { cityName: "توحید" },
                        { cityName: "دهلران" },
                        { cityName: "لومار" },
                        { cityName: "چوار" },
                        { cityName: "زرنه" },
                        { cityName: "صالح آباد" },
                        { cityName: "سرابله" },
                        { cityName: "ماژین" },
                        { cityName: "دلگشا" }
                    ]
            },
            {
                stateName: "بوشهر", cities:
                    [
                        { cityName: "آب پخش" },
                        { cityName: "ریز" },
                        { cityName: "برازجان" },
                        { cityName: "بندرریگ" },
                        { cityName: "اهرم" },
                        { cityName: "دوراهک" },
                        { cityName: "خورموج" },
                        { cityName: "نخل تقی" },
                        { cityName: "کلمه" },
                        { cityName: "بندردیلم" },
                        { cityName: "وحدتیه" },
                        { cityName: "بنک" },
                        { cityName: "چغادک" },
                        { cityName: "بندردیر" },
                        { cityName: "کاکی" },
                        { cityName: "جم" },
                        { cityName: "دالکی" },
                        { cityName: "بندرگناوه" },
                        { cityName: "آباد" },
                        { cityName: "آبدان" },
                        { cityName: "خارک" },
                        { cityName: "شنبه" },
                        { cityName: "بوشکان" },
                        { cityName: "انارستان" },
                        { cityName: "شبانکاره" },
                        { cityName: "سیراف" },
                        { cityName: "دلوار" },
                        { cityName: "بردستان" },
                        { cityName: "بادوله" },
                        { cityName: "عسلویه" },
                        { cityName: "تنگ ارم" },
                        { cityName: "امام حسن" },
                        { cityName: "سعد آباد" },
                        { cityName: "بندرکنگان" },
                        { cityName: "بوشهر" },
                        { cityName: "بردخون" },
                        { cityName: "آب پخش" }
                    ]
            },
            {
                stateName: "تهران", cities:
                    [
                        { cityName: "پردیس" },
                        { cityName: "شاهدشهر" },
                        { cityName: "پیشوا" },
                        { cityName: "جوادآباد" },
                        { cityName: "ارجمند" },
                        { cityName: "ری" },
                        { cityName: "نصیرشهر" },
                        { cityName: "رودهن" },
                        { cityName: "اندیشه" },
                        { cityName: "نسیم شهر" },
                        { cityName: "صباشهر" },
                        { cityName: "ملارد" },
                        { cityName: "شمشک" },
                        { cityName: "پاکدشت" },
                        { cityName: "باقرشهر" },
                        { cityName: "احمد آباد مستوفی" },
                        { cityName: "کیلان" },
                        { cityName: "قرچک" },
                        { cityName: "فردوسیه" },
                        { cityName: "گلستان" },
                        { cityName: "ورامین" },
                        { cityName: "فیروزکوه" },
                        { cityName: "فشم" },
                        { cityName: "پرند" },
                        { cityName: "آبعلی" },
                        { cityName: "چهاردانگه" },
                        { cityName: "تهران" },
                        { cityName: "بومهن" },
                        { cityName: "وحیدیه" },
                        { cityName: "صفادشت" },
                        { cityName: "لواسان" },
                        { cityName: "فرون اباد" },
                        { cityName: "کهریزک" },
                        { cityName: "رباطکریم" },
                        { cityName: "آبسرد" },
                        { cityName: "باغستان" },
                        { cityName: "صالحیه" },
                        { cityName: "شهریار" },
                        { cityName: "قدس" },
                        { cityName: "تجریش" },
                        { cityName: "شریف آباد" },
                        { cityName: "حسن آباد" },
                        { cityName: "اسلامشهر" },
                        { cityName: "دماوند" },
                        { cityName: "پردیس" }
                    ]
            },
            {
                stateName: "چهارمحال و بختیاری", cities:
                    [
                        { cityName: "مال خلیفه" },
                        { cityName: "وردنجان" },
                        { cityName: "گوجان" },
                        { cityName: "گهرو" },
                        { cityName: "سورشجان" },
                        { cityName: "سرخون" },
                        { cityName: "شهرکرد" },
                        { cityName: "منج" },
                        { cityName: "بروجن" },
                        { cityName: "پردنجان" },
                        { cityName: "سامان" },
                        { cityName: "فرخ شهر" },
                        { cityName: "صمصامی" },
                        { cityName: "طاقانک" },
                        { cityName: "کاج" },
                        { cityName: "نقنه" },
                        { cityName: "لردگان" },
                        { cityName: "باباحیدر" },
                        { cityName: "دستنا" },
                        { cityName: "سودجان" },
                        { cityName: "بازفت" },
                        { cityName: "هفشجان" },
                        { cityName: "سردشت" },
                        { cityName: "فرادبنه" },
                        { cityName: "چلیچه" },
                        { cityName: "بن" },
                        { cityName: "فارسان" },
                        { cityName: "شلمزار" },
                        { cityName: "نافچ" },
                        { cityName: "دشتک" },
                        { cityName: "بلداجی" },
                        { cityName: "آلونی" },
                        { cityName: "گندمان" },
                        { cityName: "جونقان" },
                        { cityName: "ناغان" },
                        { cityName: "هارونی" },
                        { cityName: "چلگرد" },
                        { cityName: "کیان" },
                        { cityName: "اردل" },
                        { cityName: "سفیددشت" },
                        { cityName: "مال خلیفه" }
                    ]
            },
            {
                stateName: "خراسان جنوبی", cities:
                    [
                        { cityName: "زهان" },
                        { cityName: "اسلامیه" },
                        { cityName: "شوسف" },
                        { cityName: "قاین" },
                        { cityName: "عشق آباد" },
                        { cityName: "طبس مسینا" },
                        { cityName: "ارسک" },
                        { cityName: "آیسک" },
                        { cityName: "نیمبلوک" },
                        { cityName: "دیهوک" },
                        { cityName: "سربیشه" },
                        { cityName: "محمدشهر" },
                        { cityName: "بیرجند" },
                        { cityName: "فردوس" },
                        { cityName: "نهبندان" },
                        { cityName: "اسفدن" },
                        { cityName: "گزیک" },
                        { cityName: "حاجی آباد" },
                        { cityName: "سه قلعه" },
                        { cityName: "آرین شهر" },
                        { cityName: "مود" },
                        { cityName: "خوسف" },
                        { cityName: "قهستان" },
                        { cityName: "بشرویه" },
                        { cityName: "سرایان" },
                        { cityName: "خضری دشت بیاض" },
                        { cityName: "طبس" },
                        { cityName: "اسدیه" },
                        { cityName: "زهان" }
                    ]
            },
            {
                stateName: "خراسان رضوی", cities:
                    [
                        { cityName: "خلیل آباد" },
                        { cityName: "بار" },
                        { cityName: "نیل شهر" },
                        { cityName: "جنگل" },
                        { cityName: "درود" },
                        { cityName: "رباط سنگ" },
                        { cityName: "سلطان آباد" },
                        { cityName: "فریمان" },
                        { cityName: "گناباد" },
                        { cityName: "کاریز" },
                        { cityName: "همت آباد" },
                        { cityName: "سلامی" },
                        { cityName: "باجگیران" },
                        { cityName: "بجستان" },
                        { cityName: "چناران" },
                        { cityName: "درگز" },
                        { cityName: "کلات" },
                        { cityName: "چکنه" },
                        { cityName: "نصرآباد" },
                        { cityName: "بردسکن" },
                        { cityName: "مشهد" },
                        { cityName: "کدکن" },
                        { cityName: "نقاب" },
                        { cityName: "قلندرآباد" },
                        { cityName: "کاشمر" },
                        { cityName: "شاندیز" },
                        { cityName: "نشتیفان" },
                        { cityName: "ششتمد" },
                        { cityName: "شادمهر" },
                        { cityName: "عشق آباد" },
                        { cityName: "چاپشلو" },
                        { cityName: "رشتخوار" },
                        { cityName: "قدمگاه" },
                        { cityName: "صالح آباد" },
                        { cityName: "داورزن" },
                        { cityName: "فرهادگرد" },
                        { cityName: "کاخک" },
                        { cityName: "مشهدریزه" },
                        { cityName: "جغتای" },
                        { cityName: "مزدآوند" },
                        { cityName: "قوچان" },
                        { cityName: "یونسی" },
                        { cityName: "سنگان" },
                        { cityName: "نوخندان" },
                        { cityName: "کندر" },
                        { cityName: "نیشابور" },
                        { cityName: "احمدابادصولت" },
                        { cityName: "شهراباد" },
                        { cityName: "رضویه" },
                        { cityName: "تربت حیدریه" },
                        { cityName: "باخرز" },
                        { cityName: "سفیدسنگ" },
                        { cityName: "بیدخت" },
                        { cityName: "تایباد" },
                        { cityName: "فیروزه" },
                        { cityName: "قاسم آباد" },
                        { cityName: "سبزوار" },
                        { cityName: "فیض آباد" },
                        { cityName: "گلمکان" },
                        { cityName: "لطف آباد" },
                        { cityName: "شهرزو" },
                        { cityName: "خرو" },
                        { cityName: "تربت جام" },
                        { cityName: "انابد" },
                        { cityName: "ملک آباد" },
                        { cityName: "بایک" },
                        { cityName: "دولت آباد" },
                        { cityName: "سرخس" },
                        { cityName: "ریوش" },
                        { cityName: "طرقبه" },
                        { cityName: "خواف" },
                        { cityName: "روداب" },
                        { cityName: "خلیل آباد" }
                    ]
            },
            {
                stateName: "خراسان شمالی", cities:
                    [
                        { cityName: "لوجلی" },
                        { cityName: "چناران شهر" },
                        { cityName: "راز" },
                        { cityName: "پیش قلعه" },
                        { cityName: "قوشخانه" },
                        { cityName: "شوقان" },
                        { cityName: "اسفراین" },
                        { cityName: "گرمه" },
                        { cityName: "قاضی" },
                        { cityName: "شیروان" },
                        { cityName: "حصارگرمخان" },
                        { cityName: "آشخانه" },
                        { cityName: "تیتکانلو" },
                        { cityName: "جاجرم" },
                        { cityName: "بجنورد" },
                        { cityName: "درق" },
                        { cityName: "آوا" },
                        { cityName: "زیارت" },
                        { cityName: "سنخواست" },
                        { cityName: "صفی آباد" },
                        { cityName: "ایور" },
                        { cityName: "فاروج" },
                        { cityName: "لوجلی" }
                    ]
            },
            {
                stateName: "خوزستان", cities:
                    [
                        { cityName: "صفی آباد" },
                        { cityName: "هفتگل" },
                        { cityName: "بیدروبه" },
                        { cityName: "شاوور" },
                        { cityName: "حمزه" },
                        { cityName: "گتوند" },
                        { cityName: "شرافت" },
                        { cityName: "منصوریه" },
                        { cityName: "زهره" },
                        { cityName: "رامهرمز" },
                        { cityName: "بندرامام خمینی" },
                        { cityName: "کوت عبداله" },
                        { cityName: "میداود" },
                        { cityName: "چغامیش" },
                        { cityName: "ملاثانی" },
                        { cityName: "چم گلک" },
                        { cityName: "حر" },
                        { cityName: "شمس آباد" },
                        { cityName: "آبژدان" },
                        { cityName: "چویبده" },
                        { cityName: "مسجدسلیمان" },
                        { cityName: "مقاومت" },
                        { cityName: "ترکالکی" },
                        { cityName: "دارخوین" },
                        { cityName: "سردشت" },
                        { cityName: "لالی" },
                        { cityName: "کوت سیدنعیم" },
                        { cityName: "حمیدیه" },
                        { cityName: "دهدز" },
                        { cityName: "قلعه تل" },
                        { cityName: "میانرود" },
                        { cityName: "رفیع" },
                        { cityName: "اندیمشک" },
                        { cityName: "الوان" },
                        { cityName: "سالند" },
                        { cityName: "صالح شهر" },
                        { cityName: "اروندکنار" },
                        { cityName: "سرداران" },
                        { cityName: "تشان" },
                        { cityName: "رامشیر" },
                        { cityName: "شادگان" },
                        { cityName: "بندرماهشهر" },
                        { cityName: "جایزان" },
                        { cityName: "بستان" },
                        { cityName: "ویس" },
                        { cityName: "اهواز" },
                        { cityName: "فتح المبین" },
                        { cityName: "شهر امام" },
                        { cityName: "قلعه خواجه" },
                        { cityName: "حسینیه" },
                        { cityName: "گلگیر" },
                        { cityName: "مینوشهر" },
                        { cityName: "سماله" },
                        { cityName: "شوشتر" },
                        { cityName: "بهبهان" },
                        { cityName: "هندیجان" },
                        { cityName: "ابوحمیظه" },
                        { cityName: "آغاجاری" },
                        { cityName: "ایذه" },
                        { cityName: "صیدون" },
                        { cityName: "سیاه منصور" },
                        { cityName: "هویزه" },
                        { cityName: "آزادی" },
                        { cityName: "شوش" },
                        { cityName: "دزفول" },
                        { cityName: "جنت مکان" },
                        { cityName: "آبادان" },
                        { cityName: "گوریه" },
                        { cityName: "خرمشهر" },
                        { cityName: "مشراگه" },
                        { cityName: "خنافره" },
                        { cityName: "چمران" },
                        { cityName: "امیدیه" },
                        { cityName: "سوسنگرد" },
                        { cityName: "شیبان" },
                        { cityName: "الهایی" },
                        { cityName: "باغ ملک" },
                        { cityName: "صفی آباد" }
                    ]
            },
            {
                stateName: "زنجان", cities:
                    [
                        { cityName: "زرین آباد" },
                        { cityName: "سجاس" },
                        { cityName: "زرین رود" },
                        { cityName: "آب بر" },
                        { cityName: "ارمغانخانه" },
                        { cityName: "کرسف" },
                        { cityName: "هیدج" },
                        { cityName: "سلطانیه" },
                        { cityName: "خرمدره" },
                        { cityName: "نیک پی" },
                        { cityName: "قیدار" },
                        { cityName: "ابهر" },
                        { cityName: "دندی" },
                        { cityName: "حلب" },
                        { cityName: "نوربهار" },
                        { cityName: "گرماب" },
                        { cityName: "چورزق" },
                        { cityName: "زنجان" },
                        { cityName: "سهرورد" },
                        { cityName: "صایین قلعه" },
                        { cityName: "ماه نشان" },
                        { cityName: "زرین آباد" }
                    ]
            },
            {
                stateName: "سمنان", cities:
                    [
                        { cityName: "آرادان" },
                        { cityName: "ایوانکی" },
                        { cityName: "مجن" },
                        { cityName: "دامغان" },
                        { cityName: "سرخه" },
                        { cityName: "مهدی شهر" },
                        { cityName: "شاهرود" },
                        { cityName: "سمنان" },
                        { cityName: "کهن آباد" },
                        { cityName: "گرمسار" },
                        { cityName: "کلاته خیج" },
                        { cityName: "دیباج" },
                        { cityName: "درجزین" },
                        { cityName: "رودیان" },
                        { cityName: "بسطام" },
                        { cityName: "امیریه" },
                        { cityName: "میامی" },
                        { cityName: "شهمیرزاد" },
                        { cityName: "بیارجمند" },
                        { cityName: "کلاته" },
                        { cityName: "آرادان" }
                    ]
            },
            {
                stateName: "سیستان و بلوچستان", cities:
                    [
                        { cityName: "نیک شهر" },
                        { cityName: "محمدی" },
                        { cityName: "شهرک علی اکبر" },
                        { cityName: "بنجار" },
                        { cityName: "گلمورتی" },
                        { cityName: "نگور" },
                        { cityName: "راسک" },
                        { cityName: "بنت" },
                        { cityName: "قصرقند" },
                        { cityName: "جالق" },
                        { cityName: "هیدوچ" },
                        { cityName: "نوک آباد" },
                        { cityName: "زهک" },
                        { cityName: "بمپور" },
                        { cityName: "پیشین" },
                        { cityName: "گشت" },
                        { cityName: "محمدآباد" },
                        { cityName: "زاهدان" },
                        { cityName: "زابلی" },
                        { cityName: "چاه بهار" },
                        { cityName: "زرآباد" },
                        { cityName: "بزمان" },
                        { cityName: "اسپکه" },
                        { cityName: "فنوج" },
                        { cityName: "سراوان" },
                        { cityName: "ادیمی" },
                        { cityName: "زابل" },
                        { cityName: "دوست محمد" },
                        { cityName: "ایرانشهر" },
                        { cityName: "سرباز" },
                        { cityName: "سیرکان" },
                        { cityName: "میرجاوه" },
                        { cityName: "نصرت آباد" },
                        { cityName: "سوران" },
                        { cityName: "خاش" },
                        { cityName: "کنارک" },
                        { cityName: "محمدان" },
                        { cityName: "نیک شهر" }
                    ]
            },
            {
                stateName: "فارس", cities:
                    [
                        { cityName: "لامرد" },
                        { cityName: "کازرون" },
                        { cityName: "کارزین (فتح آباد)" },
                        { cityName: "فدامی" },
                        { cityName: "خومه زار" },
                        { cityName: "سلطان شهر" },
                        { cityName: "فیروزآباد" },
                        { cityName: "دبیران" },
                        { cityName: "باب انار" },
                        { cityName: "رامجرد" },
                        { cityName: "سروستان" },
                        { cityName: "قره بلاغ" },
                        { cityName: "ارسنجان" },
                        { cityName: "دژکرد" },
                        { cityName: "بیرم" },
                        { cityName: "دهرم" },
                        { cityName: "شیراز" },
                        { cityName: "ایزدخواست" },
                        { cityName: "علامرودشت" },
                        { cityName: "اوز" },
                        { cityName: "وراوی" },
                        { cityName: "بیضا" },
                        { cityName: "نی ریز" },
                        { cityName: "کنارتخته" },
                        { cityName: "امام شهر" },
                        { cityName: "جهرم" },
                        { cityName: "بابامنیر" },
                        { cityName: "گراش" },
                        { cityName: "فسا" },
                        { cityName: "شهرپیر" },
                        { cityName: "حسن اباد" },
                        { cityName: "کامفیروز" },
                        { cityName: "خنج" },
                        { cityName: "خانه زنیان" },
                        { cityName: "استهبان" },
                        { cityName: "بوانات" },
                        { cityName: "لطیفی" },
                        { cityName: "فراشبند" },
                        { cityName: "زرقان" },
                        { cityName: "صغاد" },
                        { cityName: "اشکنان" },
                        { cityName: "قایمیه" },
                        { cityName: "گله دار" },
                        { cityName: "دوبرجی" },
                        { cityName: "آباده طشک" },
                        { cityName: "خرامه" },
                        { cityName: "میمند" },
                        { cityName: "افزر" },
                        { cityName: "دوزه" },
                        { cityName: "سیدان" },
                        { cityName: "کوپن" },
                        { cityName: "زاهدشهر" },
                        { cityName: "قادراباد" },
                        { cityName: "سده" },
                        { cityName: "بنارویه" },
                        { cityName: "سعادت شهر" },
                        { cityName: "شهرصدرا" },
                        { cityName: "سورمق" },
                        { cityName: "حسامی" },
                        { cityName: "جویم" },
                        { cityName: "خوزی" },
                        { cityName: "اردکان" },
                        { cityName: "قطرویه" },
                        { cityName: "نودان" },
                        { cityName: "مبارک آباددیز" },
                        { cityName: "داراب" },
                        { cityName: "نورآباد" },
                        { cityName: "کوار" },
                        { cityName: "نوبندگان" },
                        { cityName: "حاجی آباد" },
                        { cityName: "خاوران" },
                        { cityName: "مرودشت" },
                        { cityName: "کوهنجان" },
                        { cityName: "ششده" },
                        { cityName: "مزایجان" },
                        { cityName: "ایج" },
                        { cityName: "خور" },
                        { cityName: "نوجین" },
                        { cityName: "لپویی" },
                        { cityName: "بهمن" },
                        { cityName: "اهل" },
                        { cityName: "خشت" },
                        { cityName: "مهر" },
                        { cityName: "جنت شهر" },
                        { cityName: "مشکان" },
                        { cityName: "بالاده" },
                        { cityName: "قیر" },
                        { cityName: "قطب آباد" },
                        { cityName: "خانیمن" },
                        { cityName: "مصیری" },
                        { cityName: "میانشهر" },
                        { cityName: "صفاشهر" },
                        { cityName: "اقلید" },
                        { cityName: "عمادده" },
                        { cityName: "مادرسلیمان" },
                        { cityName: "داریان" },
                        { cityName: "رونیز" },
                        { cityName: "کره ای" },
                        { cityName: "لار" },
                        { cityName: "اسیر" },
                        { cityName: "هماشهر" },
                        { cityName: "آباده" },
                        { cityName: "لامرد" }
                    ]
            },
            {
                stateName: "قزوین", cities:
                    [
                        { cityName: "تاکستان" },
                        { cityName: "سگزآباد" },
                        { cityName: "بیدستان" },
                        { cityName: "کوهین" },
                        { cityName: "رازمیان" },
                        { cityName: "خرمدشت" },
                        { cityName: "آبگرم" },
                        { cityName: "شال" },
                        { cityName: "شریفیه" },
                        { cityName: "اقبالیه" },
                        { cityName: "نرجه" },
                        { cityName: "ارداق" },
                        { cityName: "الوند" },
                        { cityName: "خاکعلی" },
                        { cityName: "سیردان" },
                        { cityName: "ضیاڈآباد" },
                        { cityName: "بویین زهرا" },
                        { cityName: "محمدیه" },
                        { cityName: "محمودآبادنمونه" },
                        { cityName: "معلم کلایه" },
                        { cityName: "اسفرورین" },
                        { cityName: "آوج" },
                        { cityName: "دانسفهان" },
                        { cityName: "آبیک" },
                        { cityName: "قزوین" },
                        { cityName: "تاکستان" }
                    ]
            },
            {
                stateName: "قم", cities:
                    [
                        { cityName: "دستجرد" },
                        { cityName: "کهک" },
                        { cityName: "قم" },
                        { cityName: "سلفچگان" },
                        { cityName: "جعفریه" },
                        { cityName: "قنوات" },
                        { cityName: "دستجرد" }
                    ]
            },
            {
                stateName: "کردستان", cities:
                    [
                        { cityName: "چناره" },
                        { cityName: "قروه" },
                        { cityName: "توپ آغاج" },
                        { cityName: "سروآباد" },
                        { cityName: "بویین سفلی" },
                        { cityName: "زرینه" },
                        { cityName: "دلبران" },
                        { cityName: "سنندج" },
                        { cityName: "یاسوکند" },
                        { cityName: "موچش" },
                        { cityName: "بانه" },
                        { cityName: "مریوان" },
                        { cityName: "سریش آباد" },
                        { cityName: "صاحب" },
                        { cityName: "دهگلان" },
                        { cityName: "بابارشانی" },
                        { cityName: "دیواندره" },
                        { cityName: "برده رشه" },
                        { cityName: "شویشه" },
                        { cityName: "بیجار" },
                        { cityName: "اورامان تخت" },
                        { cityName: "کانی سور" },
                        { cityName: "کانی دینار" },
                        { cityName: "دزج" },
                        { cityName: "سقز" },
                        { cityName: "بلبان آباد" },
                        { cityName: "پیرتاج" },
                        { cityName: "کامیاران" },
                        { cityName: "آرمرده" },
                        { cityName: "چناره" }
                    ]
            },
            {
                stateName: "کرمان", cities:
                    [
                        { cityName: "انار" },
                        { cityName: "کهنوج" },
                        { cityName: "بلوک" },
                        { cityName: "پاریز" },
                        { cityName: "گنبکی" },
                        { cityName: "زنگی آباد" },
                        { cityName: "بم" },
                        { cityName: "خانوک" },
                        { cityName: "کیانشهر" },
                        { cityName: "جوپار" },
                        { cityName: "عنبرآباد" },
                        { cityName: "جوزم" },
                        { cityName: "نظام شهر" },
                        { cityName: "لاله زار" },
                        { cityName: "کشکوییه" },
                        { cityName: "زیدآباد" },
                        { cityName: "هنزا" },
                        { cityName: "چترود" },
                        { cityName: "جبالبارز" },
                        { cityName: "سیرجان" },
                        { cityName: "رودبار" },
                        { cityName: "کرمان" },
                        { cityName: "بافت" },
                        { cityName: "صفاییه" },
                        { cityName: "منوجان" },
                        { cityName: "اندوهجرد" },
                        { cityName: "هجدک" },
                        { cityName: "خورسند" },
                        { cityName: "امین شهر" },
                        { cityName: "بردسیر" },
                        { cityName: "رفسنجان" },
                        { cityName: "هماشهر" },
                        { cityName: "محمدآباد" },
                        { cityName: "اختیارآباد" },
                        { cityName: "بروات" },
                        { cityName: "ریحان" },
                        { cityName: "کوهبنان" },
                        { cityName: "ماهان" },
                        { cityName: "دوساری" },
                        { cityName: "دهج" },
                        { cityName: "فاریاب" },
                        { cityName: "گلزار" },
                        { cityName: "بهرمان" },
                        { cityName: "بلورد" },
                        { cityName: "فهرج" },
                        { cityName: "کاظم آباد" },
                        { cityName: "جیرفت" },
                        { cityName: "نجف شهر" },
                        { cityName: "قلعه گنج" },
                        { cityName: "باغین" },
                        { cityName: "بزنجان" },
                        { cityName: "زرند" },
                        { cityName: "نودژ" },
                        { cityName: "گلباف" },
                        { cityName: "راور" },
                        { cityName: "خاتون اباد" },
                        { cityName: "نرماشیر" },
                        { cityName: "دشتکار" },
                        { cityName: "مس سرچشمه" },
                        { cityName: "خواجو شهر" },
                        { cityName: "رابر" },
                        { cityName: "راین" },
                        { cityName: "درب بهشت" },
                        { cityName: "یزدان شهر" },
                        { cityName: "زهکلوت" },
                        { cityName: "محی آباد" },
                        { cityName: "مردهک" },
                        { cityName: "شهداد" },
                        { cityName: "ارزوییه" },
                        { cityName: "نگار" },
                        { cityName: "شهربابک" },
                        { cityName: "انار" }
                    ]
            },
            {
                stateName: "کرمانشاه", cities:
                    [
                        { cityName: "گودین" },
                        { cityName: "سنقر" },
                        { cityName: "شاهو" },
                        { cityName: "بانوره" },
                        { cityName: "تازه آباد" },
                        { cityName: "هلشی" },
                        { cityName: "جوانرود" },
                        { cityName: "قصرشیرین" },
                        { cityName: "نوسود" },
                        { cityName: "کرند" },
                        { cityName: "کوزران" },
                        { cityName: "بیستون" },
                        { cityName: "حمیل" },
                        { cityName: "گیلانغرب" },
                        { cityName: "سطر" },
                        { cityName: "روانسر" },
                        { cityName: "پاوه" },
                        { cityName: "ازگله" },
                        { cityName: "کرمانشاه" },
                        { cityName: "میان راهان" },
                        { cityName: "کنگاور" },
                        { cityName: "سرپل ذهاب" },
                        { cityName: "ریجاب" },
                        { cityName: "باینگان" },
                        { cityName: "هرسین" },
                        { cityName: "اسلام آبادغرب" },
                        { cityName: "سرمست" },
                        { cityName: "سومار" },
                        { cityName: "نودشه" },
                        { cityName: "گهواره" },
                        { cityName: "رباط" },
                        { cityName: "صحنه" },
                        { cityName: "گودین" }
                    ]
            },
            {
                stateName: "کهگیلویه وبویراحمد", cities:
                    [
                        { cityName: "سوق" },
                        { cityName: "گراب سفلی" },
                        { cityName: "لنده" },
                        { cityName: "سی سخت" },
                        { cityName: "دهدشت" },
                        { cityName: "یاسوج" },
                        { cityName: "سرفاریاب" },
                        { cityName: "دوگنبدان" },
                        { cityName: "چیتاب" },
                        { cityName: "لیکک" },
                        { cityName: "دیشموک" },
                        { cityName: "مادوان" },
                        { cityName: "باشت" },
                        { cityName: "پاتاوه" },
                        { cityName: "قلعه رییسی" },
                        { cityName: "مارگون" },
                        { cityName: "چرام" },
                        { cityName: "سوق" }
                    ]
            },
            {
                stateName: "گلستان", cities:
                    [
                        { cityName: "جلین" },
                        { cityName: "سیمین شهر" },
                        { cityName: "مزرعه" },
                        { cityName: "رامیان" },
                        { cityName: "فراغی" },
                        { cityName: "گنبدکاووس" },
                        { cityName: "کردکوی" },
                        { cityName: "مراوه" },
                        { cityName: "بندرترکمن" },
                        { cityName: "نگین شهر" },
                        { cityName: "آق قلا" },
                        { cityName: "سرخنکلاته" },
                        { cityName: "گالیکش" },
                        { cityName: "سنگدوین" },
                        { cityName: "دلند" },
                        { cityName: "بندرگز" },
                        { cityName: "نوده خاندوز" },
                        { cityName: "مینودشت" },
                        { cityName: "گرگان" },
                        { cityName: "گمیش تپه" },
                        { cityName: "علی اباد" },
                        { cityName: "خان ببین" },
                        { cityName: "کلاله" },
                        { cityName: "اینچه برون" },
                        { cityName: "فاضل آباد" },
                        { cityName: "تاتارعلیا" },
                        { cityName: "نوکنده" },
                        { cityName: "آزادشهر" },
                        { cityName: "انبارآلوم" },
                        { cityName: "جلین" }
                    ]
            },
            {
                stateName: "گیلان", cities:
                    [
                        { cityName: "رانکوه" },
                        { cityName: "منجیل" },
                        { cityName: "شلمان" },
                        { cityName: "خشکبیجار" },
                        { cityName: "ماکلوان" },
                        { cityName: "سنگر" },
                        { cityName: "مرجقل" },
                        { cityName: "لیسار" },
                        { cityName: "رضوانشهر" },
                        { cityName: "رحیم آباد" },
                        { cityName: "لوندویل" },
                        { cityName: "احمدسرگوراب" },
                        { cityName: "لوشان" },
                        { cityName: "اطاقور" },
                        { cityName: "لشت نشاء" },
                        { cityName: "فومن" },
                        { cityName: "چوبر" },
                        { cityName: "بازار جمعه" },
                        { cityName: "کلاچای" },
                        { cityName: "بندرانزلی" },
                        { cityName: "املش" },
                        { cityName: "رستم آباد" },
                        { cityName: "لاهیجان" },
                        { cityName: "توتکابن" },
                        { cityName: "لنگرود" },
                        { cityName: "کوچصفهان" },
                        { cityName: "صومعه سرا" },
                        { cityName: "اسالم" },
                        { cityName: "دیلمان" },
                        { cityName: "رودسر" },
                        { cityName: "کیاشهر" },
                        { cityName: "شفت" },
                        { cityName: "رودبار" },
                        { cityName: "کومله" },
                        { cityName: "رشت" },
                        { cityName: "ماسوله" },
                        { cityName: "خمام" },
                        { cityName: "ماسال" },
                        { cityName: "واجارگاه" },
                        { cityName: "هشتپر (تالش)" },
                        { cityName: "پره سر" },
                        { cityName: "بره سر" },
                        { cityName: "آستارا" },
                        { cityName: "رودبنه" },
                        { cityName: "جیرنده" },
                        { cityName: "چاف و چمخاله" },
                        { cityName: "لولمان" },
                        { cityName: "گوراب زرمیخ" },
                        { cityName: "حویق" },
                        { cityName: "سیاهکل" },
                        { cityName: "چابکسر" },
                        { cityName: "آستانه اشرفیه" },
                        { cityName: "رانکوه" }
                    ]
            },
            {
                stateName: "لرستان", cities:
                    [
                        { cityName: "درب گنبد" },
                        { cityName: "چالانچولان" },
                        { cityName: "بیران شهر" },
                        { cityName: "ویسیان" },
                        { cityName: "شول آباد" },
                        { cityName: "پلدختر" },
                        { cityName: "کوهدشت" },
                        { cityName: "هفت چشمه" },
                        { cityName: "بروجرد" },
                        { cityName: "الشتر" },
                        { cityName: "مومن آباد" },
                        { cityName: "دورود" },
                        { cityName: "زاغه" },
                        { cityName: "چقابل" },
                        { cityName: "الیگودرز" },
                        { cityName: "معمولان" },
                        { cityName: "کوهنانی" },
                        { cityName: "نورآباد" },
                        { cityName: "سپیددشت" },
                        { cityName: "سراب دوره" },
                        { cityName: "ازنا" },
                        { cityName: "گراب" },
                        { cityName: "خرم آباد" },
                        { cityName: "اشترینان" },
                        { cityName: "فیروزآباد" },
                        { cityName: "درب گنبد" }
                    ]
            },
            {
                stateName: "مازندران", cities:
                    [
                        { cityName: "چمستان" },
                        { cityName: "گلوگاه" },
                        { cityName: "گلوگاه" },
                        { cityName: "پل سفید" },
                        { cityName: "دابودشت" },
                        { cityName: "چالوس" },
                        { cityName: "کیاسر" },
                        { cityName: "بهنمیر" },
                        { cityName: "تنکابن" },
                        { cityName: "کلاردشت" },
                        { cityName: "ایزدشهر" },
                        { cityName: "گتاب" },
                        { cityName: "سلمان شهر" },
                        { cityName: "ارطه" },
                        { cityName: "امیرکلا" },
                        { cityName: "کوهی خیل" },
                        { cityName: "پایین هولار" },
                        { cityName: "گزنک" },
                        { cityName: "محمودآباد" },
                        { cityName: "رامسر" },
                        { cityName: "نوشهر" },
                        { cityName: "خلیل شهر" },
                        { cityName: "کیاکلا" },
                        { cityName: "نور" },
                        { cityName: "مرزیکلا" },
                        { cityName: "فریدونکنار" },
                        { cityName: "زیرآب" },
                        { cityName: "امامزاده عبدالله" },
                        { cityName: "هچیرود" },
                        { cityName: "فریم" },
                        { cityName: "هادی شهر" },
                        { cityName: "نشتارود" },
                        { cityName: "پول" },
                        { cityName: "بهشهر" },
                        { cityName: "کلارآباد" },
                        { cityName: "بلده" },
                        { cityName: "بابل" },
                        { cityName: "جویبار" },
                        { cityName: "آلاشت" },
                        { cityName: "آمل" },
                        { cityName: "نکا" },
                        { cityName: "کتالم وسادات شهر" },
                        { cityName: "بابلسر" },
                        { cityName: "شیرود" },
                        { cityName: "شیرگاه" },
                        { cityName: "رویان" },
                        { cityName: "زرگرمحله" },
                        { cityName: "عباس اباد" },
                        { cityName: "قایم شهر" },
                        { cityName: "خوش رودپی" },
                        { cityName: "مرزن آباد" },
                        { cityName: "ساری" },
                        { cityName: "رینه" },
                        { cityName: "سرخرود" },
                        { cityName: "خرم آباد" },
                        { cityName: "کجور" },
                        { cityName: "رستمکلا" },
                        { cityName: "سورک" },
                        { cityName: "چمستان" }
                    ]
            },
            {
                stateName: "مرکزی", cities:
                    [
                        { cityName: "شهباز" },
                        { cityName: "آستانه" },
                        { cityName: "خنجین" },
                        { cityName: "نراق" },
                        { cityName: "کمیجان" },
                        { cityName: "آشتیان" },
                        { cityName: "رازقان" },
                        { cityName: "مهاجران" },
                        { cityName: "غرق آباد" },
                        { cityName: "خنداب" },
                        { cityName: "قورچی باشی" },
                        { cityName: "خشکرود" },
                        { cityName: "ساروق" },
                        { cityName: "محلات" },
                        { cityName: "شازند" },
                        { cityName: "ساوه" },
                        { cityName: "میلاجرد" },
                        { cityName: "تفرش" },
                        { cityName: "زاویه" },
                        { cityName: "اراک" },
                        { cityName: "توره" },
                        { cityName: "نوبران" },
                        { cityName: "فرمهین" },
                        { cityName: "دلیجان" },
                        { cityName: "پرندک" },
                        { cityName: "کارچان" },
                        { cityName: "نیمور" },
                        { cityName: "هندودر" },
                        { cityName: "آوه" },
                        { cityName: "جاورسیان" },
                        { cityName: "خمین" },
                        { cityName: "مامونیه" },
                        { cityName: "داودآباد" },
                        { cityName: "شهباز" }
                    ]
            },
            {
                stateName: "هرمزگان", cities:
                    [
                        { cityName: "تخت" },
                        { cityName: "بیکاء" },
                        { cityName: "تیرور" },
                        { cityName: "گروک" },
                        { cityName: "قشم" },
                        { cityName: "کوشکنار" },
                        { cityName: "کیش" },
                        { cityName: "سرگز" },
                        { cityName: "بندرعباس" },
                        { cityName: "زیارتعلی" },
                        { cityName: "سندرک" },
                        { cityName: "کوهستک" },
                        { cityName: "لمزان" },
                        { cityName: "رویدر" },
                        { cityName: "قلعه قاضی" },
                        { cityName: "فارغان" },
                        { cityName: "ابوموسی" },
                        { cityName: "هشتبندی" },
                        { cityName: "سردشت" },
                        { cityName: "درگهان" },
                        { cityName: "پارسیان" },
                        { cityName: "کنگ" },
                        { cityName: "جناح" },
                        { cityName: "تازیان پایین" },
                        { cityName: "دهبارز" },
                        { cityName: "میناب" },
                        { cityName: "سیریک" },
                        { cityName: "سوزا" },
                        { cityName: "خمیر" },
                        { cityName: "چارک" },
                        { cityName: "حاجی اباد" },
                        { cityName: "فین" },
                        { cityName: "بندرجاسک" },
                        { cityName: "گوهران" },
                        { cityName: "هرمز" },
                        { cityName: "دشتی" },
                        { cityName: "بندرلنگه" },
                        { cityName: "بستک" },
                        { cityName: "تخت" }
                    ]
            },
            {
                stateName: "همدان", cities:
                    [
                        { cityName: "قهاوند" },
                        { cityName: "زنگنه" },
                        { cityName: "دمق" },
                        { cityName: "سرکان" },
                        { cityName: "آجین" },
                        { cityName: "جورقان" },
                        { cityName: "برزول" },
                        { cityName: "فامنین" },
                        { cityName: "سامن" },
                        { cityName: "بهار" },
                        { cityName: "فرسفج" },
                        { cityName: "شیرین سو" },
                        { cityName: "مریانج" },
                        { cityName: "فیروزان" },
                        { cityName: "قروه درجزین" },
                        { cityName: "ازندریان" },
                        { cityName: "لالجین" },
                        { cityName: "گل تپه" },
                        { cityName: "گیان" },
                        { cityName: "ملایر" },
                        { cityName: "صالح آباد" },
                        { cityName: "تویسرکان" },
                        { cityName: "اسدآباد" },
                        { cityName: "همدان" },
                        { cityName: "نهاوند" },
                        { cityName: "رزن" },
                        { cityName: "جوکار" },
                        { cityName: "مهاجران" },
                        { cityName: "کبودرآهنگ" },
                        { cityName: "قهاوند" }
                    ]
            },
            {
                stateName: "یزد", cities:
                    [
                        { cityName: "احمدآباد" },
                        { cityName: "مروست" },
                        { cityName: "مهردشت" },
                        { cityName: "حمیدیا" },
                        { cityName: "تفت" },
                        { cityName: "اشکذر" },
                        { cityName: "ندوشن" },
                        { cityName: "یزد" },
                        { cityName: "عقدا" },
                        { cityName: "بهاباد" },
                        { cityName: "ابرکوه" },
                        { cityName: "زارچ" },
                        { cityName: "نیر" },
                        { cityName: "اردکان" },
                        { cityName: "هرات" },
                        { cityName: "بفروییه" },
                        { cityName: "شاهدیه" },
                        { cityName: "بافق" },
                        { cityName: "خضرآباد" },
                        { cityName: "میبد" },
                        { cityName: "مهریز" },
                        { cityName: "احمدآباد" }
                    ]
            }
        ]
}